package chatbot;

public enum Intent {
    GREETING, FAREWELL, THANKS, HELP,
    WEATHER, TIME, DATE, JOKE,
    COMPLIMENT, INSULT_RESPONSE, ABOUT_BOT, CAPABILITIES,
    REPEAT, AFFIRM, DENY,
    FAQ_JAVA, FAQ_CODEALPHA,
    MATH, DEFINITION, UNKNOWN
}
